name: Continuous integration and continuos deployment
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

      - name: Run unit and integration tests with Karma
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Comment Test Coverage
        if: github.event_name == 'pull_request'
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/scalio-challenge/coverage-summary.json
          title: Karma Test Coverage

      - name: Run e2e tests with Cypress 
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:4200'
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build
        if: github.event_name == 'push'

      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.event_name == 'push'
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_SEARCH_F7F52 }}'
          channelId: live
          projectId: github-search-f7f52

      - name: Upload dist files
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/scalio-challenge
          retention-days: 1

      - name: Upload coverage result
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/scalio-challenge
          retention-days: 1