name: Deploy to Firebase Hosting on push
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

      - name: Run unit and integration tests with Karma
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Run e2e tests with Cypress 
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB_SEARCH_F7F52 }}'
          channelId: live
          projectId: github-search-f7f52
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/scalio-challenge
          retention-days: 1

